### ISSUE TITLE
[iOS] Test the app

### ISSUE THREAD

**Issue by habi** [developmentseed/observe#108]
I've seen watched [your talk at SOTM19](https://media.ccc.de/v/sotm2019-1323-observe-offline-cross-platform-field-mapping-tool-for-openstreetmap) and would love to test the app.
After watching the talk some weeks ago, I went to the [TestFairy](https://tsfr.io/observe-ios) and entered my email address.
I haven't heard anything; do you not accept any testers?

**Comment by habi** [comment]
And BTW: github.com/developmentseed/observe/ loads the `develop` branch by default.
In this branch, the README.md says nothing about testing the app...

**Comment by habi** [comment]
And second BTW: I've installed the TestFairy profile, my device is registered and 'the device ID was sent to the developer'...

**Comment by geohacker** [comment]
@habi sorry about the wait! We definitely are accepting testers. Just that in the last few weeks we embarked on a react-native version upgrade which turned out to be a daunting task -- this is now in develop and we plan to merge that with master next week and release a 0.1.9 of the app for testing.

It sounds like you've setup the profile so during the next build, I'd be able to fetch the device ID from apple and add it. Thank you for the nudge and your patience :)

**Comment by habi** [comment]
Hey, I've not heard anything in the last (nearly) four months, I'd really like to help test this thing :)

**Comment by geohacker** [comment]
I'm sorry about this @habi -- we've been hard at work, but haven't put out a release that's ready for testing. As you can see a [v0.2.0-alpha](https://github.com/developmentseed/observe/pull/158) is in the queue. This was supposed to go out in December but it didn't. We didn't release v0.1.9 as I intended. 

v0.2.0-alpha will be out next week, and you'll be among the first ones to know.

**Comment by geohacker** [comment]
@habi we just released 0.2.0-alpha. Download instructions for both Android and iOS are here https://github.com/developmentseed/observe/releases/tag/v0.2.0-alpha.

**Comment by habi** [comment]
Great, thanks!
