### ISSUE TITLE
Way is cleared after hitting "Back" on preset screen (Add Way)

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe#249]
How to replicate:

- Enter "Add Way" mode
- Draw some points
- Hit "Tick"
- Hit "<-" at preset screen

The drawn line has been cleared, when it should be kept for further editing.

## iOS capture

![bug-2](https://user-images.githubusercontent.com/329694/82823803-1dcab000-9ea0-11ea-92aa-b2960a66100b.gif)

**Comment by geohacker** [comment]
Tried this on the `edit-way-changesets` branch but not able to reproduce. cc @sethvincent

**Comment by sethvincent** [comment]
I am also not able to reproduce now. It's weird because I know I saw this happening before.

My guess is that at some point the `resetWayEditing` action was being called when going back from the preset screen but after doing some testing it definitely isn't being called now.

I think we're good to close this.
