### ISSUE TITLE
Fields collapse when deleted

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#26]
@batpad found this yesterday and I was able to reproduce - this is not a regression. When you remove a field the ones above that field seem to collapse. 

![Screenshot_20190513-143814](https://user-images.githubusercontent.com/371666/57668872-7ed16e00-7626-11e9-9a7a-16cc1f8de670.png)

@sethvincent - i tried poking around a bit, but not sure what this is exactly. perhaps something to do with the flexbox?

**Comment by geohacker** [comment]
@sethvincent this seems to be a bad one - breaks both on iOS and Android - and I can't seem to figure out why. I initially thought it might be because of the fixed width. It's consistently breaking in the add and edit screen. Let me know if you have thoughts, any pointers will be helpful!

**Comment by geohacker** [comment]
@sethvincent I think this is still a problem and a pretty bad one

**Comment by LanesGood** [comment]
Whoops, made the commit on multiple (now deleted) branches that were based off `master` instead of develop, hence the redundant commits above. 

To note:
- I was only able to reproduce the bug on "Building" features
- I also see terminal errors for react-native that stated issues with radio and url field types
- clicking "Add Field" after the delete/collapse issue restored the collapsed fields

So the fix in my PR should address the main bug, but I'm not certain about the other notes above
