### ISSUE TITLE
tile loading errors

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe#71]
An example request that is failing:

```
https://master.apis.dev.openstreetmap.org/api/0.6/map/?bbox=0,-0.005493164054076122,0.0054931640625,0
```

It probably makes sense for that to fail. Not sure how we're ending up with that bbox though.

**Comment by geohacker** [comment]
I can confirm that this is because we're loading the map with no predefined center https://github.com/developmentseed/observe/blob/d56ba9c33d34b40033b4eebeda0cb67cd100024a/app/screens/Explore.js#L394

Setting a center at the start of the map seem to fix this arbitrary bbox request. Need to do a bit more testing and make to the user locate behavior is not altered. 

cc @batpad
