### ISSUE TITLE
Ability to create and edit ways

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe#91]
_This is a high-level ticket to capture the goals and we'll spin up smaller tickets as needed_

Now that Observe can create and edit POIs, and edit attributes of ways the next we want the ability to create and edit ways. Overall:

1. Create way mode where users can draw ways 
2. Select a way and then be able to edit the geometry 
3. Select a GPX trace and turn that into a way (bonus on the phone? but would be possible on the desktop editors)

We should set some limitations:
1. Editing ways that are part of relations would be really challenging, so we should evaluate if it's necessary to allow edits to ways that are members of relations
2. The user would have to select a way or be zoomed in enough to reduce data that needs to be loaded to the memory 
3. In cases where automatic snapping isn't possible, the user would be prompted to select the nodes to snap
4. There could be more.

cc @batpad @LanesGood @sethvincent @vgeorge

**Comment by geohacker** [comment]
More thoughts.

Some assumptions:
* The user will be able to create new ways and edit geometry of existing ones
* Creation and editing will only be possible at a specified zoom level -- this allows us to restrict editing really large polygons

The biggest thing we need to introduce is to store nodes. Currently Observe throws out nodes [without tags](https://github.com/developmentseed/observe/blob/master/app/utils/filter-tags.js) before rendering the GeoJSON. Though each way has a property of all member nodes. 

## Nodecache

If we want to keep the GeoJSON format, then we should store the nodes separately in an easy-fast lookup structure. One way I think this would be useful is:
* The use selects a way for editing
* We load all the nodes of the way
* When the user changes a node, we update the node and add this to the edits
* If this node is shared by another way, we update that way?

**Comment by LanesGood** [comment]
Additional questions as I begin more research.
- Do we intend for users to be able to create areas?
- What kind of geometry editing should be possible in the app? ID options include: circularize, square, move, disconnect, rotate, reflect, reverse, delete:

/cc @developmentseed/observe

**Comment by vgeorge** [comment]
I'm not sure if this is too complex to implement, but it seems area editing is necessary to allow building mapping. Regarding geometry editing:

- Essential: reverse, delete, connect, disconnect, add/move/del way nodes
- Good to have: circularize, square
- Advanced: rotate and reflect seems to be more useful when you are copy/pasting repeated features like similar buildings in a housing complex. I'm not sure if this is a strong use case for mobile.
- Avoid: I'm not sure we should offer "move". In my editing experience, I generally avoid moving ways as a whole, because it generally affects connected ways. I prefer moving/editing/deleting way nodes instead.

**Comment by geohacker** [comment]
With #232, this is complete.
